### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by danielo515** [gt6796c/mermaid-tw5#2]
Hey!

Glad to see there is a mermaid plugin for tw5 already.
Could you please share instructions about how to install it?

Thanks in advance. 
Regards

**Comment by gt6796c** [comment]
I build it using the TW5 build instructions found 
[here](http://tiddlywiki.com/dev/#Developing%20plugins%20using%20Node.js%20and%20GitHub)

git clone <this project> into the TWROOT/plugins/gt6796c and then enable it in your edition's tiddlywiki.info file, it'll build. You can open that output and drag it into yours.

I'll look to getting it up on the tubes somewhere to share easier.

**Comment by gt6796c** [comment]
you can go to https://gt6796c.github.io and drag the plugin into your TiddlyWiki now.

**Comment by danielo515** [comment]
Thank you very much! I have detected a small bug, I'll open another issue. 

Sorry for continuing with this issue, but I don't know any other way of contacting you. 

I saw that one of your plugins includes `$:/boot/bootprefix.js`. Does it work? Does it override the core one? How is it possible that it gets executed if it is part of a plugin? 

Thanks and regards

**Comment by gt6796c** [comment]
I'm sorry, I don't see what you mean. When I open up any of the plugins, none show boot/bootprefix.js being used.

**Comment by danielo515** [comment]
What about this one? 

https://gt6796c.github.io/#%24%3A%2Fplugins%2Fgt6796c%2Frocklib%2Fwidget-tools.js

**Comment by gt6796c** [comment]
OK, I see it now. It looks to be a comment leftover from when I was trying to figure out how to have a library only plugin. I'm guessing that the comment is ignored since that particular javascript file has a tiddlywiki.info to provide the real title of the tiddler and I've got plugins looking for that file.

I'll move this #3 

I'll update the file and get it pushed out. 

Thanks!
